name: bito
channels:
  - conda-forge
  - bioconda
dependencies:
  - igraph
  - iqtree
  - matplotlib
  - mrbayes
  - newick_utils
  - pandas
  - parallel
  - pip
  - pip:
    - click
    - seqmagick
  - sortedcontainers
