set -eu

# This script prepares golden run data for explorying NNI subsplit DAG support.
# This expects to run at watching-mb/golden/ds{{ds_number}}/posterior-support.

# Convert the fasta file from the nexus file.
seqmagick convert ../data/DS{{ds_number}}.n.nex ds{{ds_number}}.fasta

# Create the newick file from the posterior pickle.
wtch-unpickle-cdf.py ../posterior.pkl ds{{ds_number}}.credible.nwk 

# Generate all the Nearest Neighbor Interchange trees.
wtch-generate-all-nnis.sh ds{{ds_number}}.credible.nwk {{reroot_number}} > ds{{ds_number}}.neighbors.nwk

# Sort the trees according to likelhood from iqtree. 
wtch-likelihood-ordering.py ds{{ds_number}}.neighbors.nwk ds{{ds_number}}.fasta ds{{ds_number}}.ordered.nwk

# Reroot on {{reroot_number}}, which is {{reroot_name}}.
nw_reroot ds{{ds_number}}.ordered.nwk {{reroot_number}} > ds{{ds_number}}.rerooted.nwk

# Run noodle to get the representations.
# Be warned, the following call will probably be too much to handle, even on the cluster.
noodle ds{{ds_number}}.fasta ds{{ds_number}}.ordered.nwk ds{{ds_number}}.rerooted.nwk ds{{ds_number}}.credible.nwk ds{{ds_number}}.representations.csv ds{{ds_number}}.credible.representations.csv

# Cleanup files generated by noodle.
rm mmapped_plv.data
